CREATE TABLE "dim_stations" (
  "station_sk_id" int PRIMARY KEY,
  "station_nk_id" int,
  "name" varchar,
  "current_latitude" float,
  "current_longitude" float,
  "current_elevation_m" float,
  "wmo_id" varchar,
  "kodebmkg_id" varchar,
  "is_active" varchar,
  "status_reason" varchar,
  "source_system" varchar,
  "station_type" varchar,
  "station_code" varchar,
  "type_mkg" varchar,
  "operating_hours" int,
  "hour_start" int,
  "hour_end" int,
  "valid_from" timestamp,
  "valid_to" timestamp,
  "kabupaten_id" int,
  "kecamatan" varchar,
  "kelurahan" varchar,
  "station_address" varchar,
  "time_zone" varchar
);

CREATE TABLE "dim_time_day" (
  "time_day_id" date PRIMARY KEY,
  "time_month_id" int,
  "time_year_id" int,
  "day_of_month" int,
  "day_name_ina" varchar,
  "day_name_eng" varchar
);

CREATE TABLE "dim_time_month" (
  "time_month_id" int PRIMARY KEY,
  "year" smallint,
  "month" smallint,
  "month_name_ina" varchar,
  "month_name_eng" varchar,
  "month_short_name_ina" varchar,
  "month_short_name_eng" varchar,
  "month_start_date" date,
  "month_end_date" date,
  "days_in_month" int
);

CREATE TABLE "dim_time_year" (
  "time_year_id" int PRIMARY KEY,
  "year" smallint,
  "days_in_year" int
);

CREATE TABLE "dim_geo_kabupaten" (
  "kabupaten_id" int PRIMARY KEY,
  "kabupaten_code_kemendagri" varchar,
  "kabupaten_code_bps" varchar,
  "kabupaten_name" varchar,
  "propinsi_id" int
);

CREATE TABLE "dim_geo_propinsi" (
  "propinsi_id" int PRIMARY KEY,
  "propinsi_code_kemendagri" varchar,
  "propinsi_code_bps" varchar,
  "propinsi_name" varchar,
  "region_id" int
);

CREATE TABLE "dim_geo_region" (
  "region_id" int PRIMARY KEY,
  "region_desc" varchar
);

CREATE TABLE "fact_bmkgsoft_me48_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_me48_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_fklim_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_fklim_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_intensitas_hujan_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_intensitas_hujan_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_penguapan_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_penguapan_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_agm1a_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_agm1a_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_agm1b_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_agm1b_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_poshujan_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_bmkgsoft_poshujan_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_awscenter_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_awscenter_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_radar_vol_availability_daily" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_day_id" date,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float,
  "radar_name" varchar,
  "folder_name" varchar,
  "path" varchar,
  "updated_at" timestamp
);

CREATE TABLE "fact_radar_vol_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_radar_vol_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_satellite_nc_availability_daily" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_day_id" date,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float,
  "satellite_name" varchar,
  "folder_name" varchar,
  "path" varchar,
  "updated_at" timestamp
);

CREATE TABLE "fact_satellite_nc_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_satellite_nc_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "total_expected_data" int,
  "total_actual_data" int,
  "percentage_available" float
);

CREATE TABLE "fact_idg_petir_ld2000_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "ldc_total_expected_data" int,
  "ldc_total_actual_data" int,
  "ldc_percentage_available" float,
  "kml_total_expected_data" int,
  "kml_total_actual_data" int,
  "kml_percentage_available" float,
  "txt_total_expected_data" int,
  "txt_total_actual_data" int,
  "txt_percentage_available" float
);

CREATE TABLE "fact_idg_petir_ld2000_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "ldc_total_expected_data" int,
  "ldc_total_actual_data" int,
  "ldc_percentage_available" float,
  "kml_total_expected_data" int,
  "kml_total_actual_data" int,
  "kml_percentage_available" float,
  "txt_total_expected_data" int,
  "txt_total_actual_data" int,
  "txt_percentage_available" float
);

CREATE TABLE "fact_idg_petir_nexstorm_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "db3_total_expected_data" int,
  "db3_total_actual_data" int,
  "db3_percentage_available" float,
  "nex_total_expected_data" int,
  "nex_total_actual_data" int,
  "nex_percentage_available" float,
  "csv_total_expected_data" int,
  "csv_total_actual_data" int,
  "csv_percentage_available" float
);

CREATE TABLE "fact_idg_petir_nexstorm_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "db3_total_expected_data" int,
  "db3_total_actual_data" int,
  "db3_percentage_available" float,
  "nex_total_expected_data" int,
  "nex_total_actual_data" int,
  "nex_percentage_available" float,
  "csv_total_expected_data" int,
  "csv_total_actual_data" int,
  "csv_percentage_available" float
);

CREATE TABLE "fact_idg_percepatan_tanah_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "ace_total_expected_data" int,
  "ace_total_actual_data" int,
  "ace_percentage_available" float,
  "acn_total_expected_data" int,
  "acn_total_actual_data" int,
  "acn_percentage_available" float,
  "acz_total_expected_data" int,
  "acz_total_actual_data" int,
  "acz_percentage_available" float
);

CREATE TABLE "fact_idg_percepatan_tanah_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "ace_total_expected_data" int,
  "ace_total_actual_data" int,
  "ace_percentage_available" float,
  "acn_total_expected_data" int,
  "acn_total_actual_data" int,
  "acn_percentage_available" float,
  "acz_total_expected_data" int,
  "acz_total_actual_data" int,
  "acz_percentage_available" float
);

CREATE TABLE "fact_idg_intensitas_gempa_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "hne_total_expected_data" int,
  "hne_total_actual_data" int,
  "hne_percentage_available" float,
  "hnn_total_expected_data" int,
  "hnn_total_actual_data" int,
  "hnn_percentage_available" float,
  "hnz_total_expected_data" int,
  "hnz_total_actual_data" int,
  "hnz_percentage_available" float
);

CREATE TABLE "fact_idg_intensitas_gempa_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "hne_total_expected_data" int,
  "hne_total_actual_data" int,
  "hne_percentage_available" float,
  "hnn_total_expected_data" int,
  "hnn_total_actual_data" int,
  "hnn_percentage_available" float,
  "hnz_total_expected_data" int,
  "hnz_total_actual_data" int,
  "hnz_percentage_available" float
);

CREATE TABLE "fact_idg_gempa_bumi_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "ew_total_expected_data" int,
  "ew_total_actual_data" int,
  "ew_percentage_available" float,
  "ns_total_expected_data" int,
  "ns_total_actual_data" int,
  "ns_percentage_available" float,
  "z_total_expected_data" int,
  "z_total_actual_data" int,
  "z_percentage_available" float
);

CREATE TABLE "fact_idg_gempa_bumi_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "ew_total_expected_data" int,
  "ew_total_actual_data" int,
  "ew_percentage_available" float,
  "ns_total_expected_data" int,
  "ns_total_actual_data" int,
  "ns_percentage_available" float,
  "z_total_expected_data" int,
  "z_total_actual_data" int,
  "z_percentage_available" float
);

CREATE TABLE "fact_idg_magnet_baseline_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "lemi_total_expected_data" int,
  "lemi_total_actual_data" int,
  "lemi_percentage_available" float,
  "proton_total_expected_data" int,
  "proton_total_actual_data" int,
  "proton_percentage_available" float
);

CREATE TABLE "fact_idg_magnet_baseline_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "lemi_total_expected_data" int,
  "lemi_total_actual_data" int,
  "lemi_percentage_available" float,
  "proton_total_expected_data" int,
  "proton_total_actual_data" int,
  "proton_percentage_available" float
);

CREATE TABLE "fact_idg_magnet_prekursor_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_month_id" int,
  "prekursor_total_expected_data" int,
  "prekursor_total_actual_data" int,
  "prekursor_percentage_available" float
);

CREATE TABLE "fact_idg_magnet_prekursor_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" int,
  "time_year_id" int,
  "prekursor_total_expected_data" int,
  "prekursor_total_actual_data" int,
  "prekursor_percentage_available" float
);

COMMENT ON TABLE "dim_time_month" IS 'Contoh data: ("202501", "2025", "01", "Januari", "January"';

COMMENT ON TABLE "dim_geo_kabupaten" IS 'Contoh data: (1, "1101", "1101", "Kabupaten Simeulue", 11)';

COMMENT ON TABLE "dim_geo_region" IS 'Contoh data: (1, "Region I"), (2, "Region II"), (3, "Region III"), (4, "Region IV"), (5, "Region V")';

ALTER TABLE "dim_stations" ADD FOREIGN KEY ("kabupaten_id") REFERENCES "dim_geo_kabupaten" ("kabupaten_id");

ALTER TABLE "dim_geo_kabupaten" ADD FOREIGN KEY ("propinsi_id") REFERENCES "dim_geo_propinsi" ("propinsi_id");

ALTER TABLE "dim_geo_propinsi" ADD FOREIGN KEY ("region_id") REFERENCES "dim_geo_region" ("region_id");

ALTER TABLE "dim_time_day" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "dim_time_month" ADD FOREIGN KEY ("year") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_radar_vol_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_radar_vol_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_radar_vol_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_radar_vol_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_satellite_nc_availability_daily" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_satellite_nc_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_satellite_nc_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_satellite_nc_availability_daily" ADD FOREIGN KEY ("time_day_id") REFERENCES "dim_time_day" ("time_day_id");

ALTER TABLE "fact_satellite_nc_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_satellite_nc_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_me48_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_me48_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_me48_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_me48_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_fklim_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_fklim_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_fklim_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_fklim_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_intensitas_hujan_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_intensitas_hujan_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_intensitas_hujan_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_intensitas_hujan_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_penguapan_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_penguapan_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_penguapan_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_penguapan_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_agm1a_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_agm1a_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_agm1a_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_agm1a_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_agm1b_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_agm1b_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_agm1b_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_agm1b_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_bmkgsoft_poshujan_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_poshujan_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_poshujan_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_bmkgsoft_poshujan_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_awscenter_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_awscenter_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_awscenter_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_awscenter_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_petir_ld2000_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_petir_ld2000_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_petir_ld2000_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_petir_ld2000_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_petir_nexstorm_availability_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_petir_nexstorm_availability_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_petir_nexstorm_availability_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_petir_nexstorm_availability_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_percepatan_tanah_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_percepatan_tanah_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_percepatan_tanah_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_percepatan_tanah_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_intensitas_gempa_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_intensitas_gempa_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_intensitas_gempa_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_intensitas_gempa_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_gempa_bumi_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_gempa_bumi_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_gempa_bumi_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_gempa_bumi_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_magnet_baseline_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_magnet_baseline_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_magnet_baseline_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_magnet_baseline_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");

ALTER TABLE "fact_idg_magnet_prekursor_monthly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_magnet_prekursor_yearly" ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_idg_magnet_prekursor_monthly" ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

ALTER TABLE "fact_idg_magnet_prekursor_yearly" ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");
