
-- =====================================
-- CREATE TABLE fact_bmkgsoft_fklim_availability_monthly
-- =====================================
CREATE TABLE "fact_bmkgsoft_fklim_availability_monthly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" INT,
  "time_month_id" INT,
  "total_expected_data" INT,
  "total_actual_data" INT,
  "percentage_available" FLOAT
);

ALTER TABLE "fact_bmkgsoft_fklim_availability_monthly"
  ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_fklim_availability_monthly"
  ADD FOREIGN KEY ("time_month_id") REFERENCES "dim_time_month" ("time_month_id");

-- =====================================
-- CREATE TABLE fact_bmkgsoft_fklim_availability_yearly
-- =====================================
CREATE TABLE "fact_bmkgsoft_fklim_availability_yearly" (
  "fact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_sk_id" INT,
  "time_year_id" INT,
  "total_expected_data" INT,
  "total_actual_data" INT,
  "percentage_available" FLOAT
);

ALTER TABLE "fact_bmkgsoft_fklim_availability_yearly"
  ADD FOREIGN KEY ("station_sk_id") REFERENCES "dim_stations" ("station_sk_id");

ALTER TABLE "fact_bmkgsoft_fklim_availability_yearly"
  ADD FOREIGN KEY ("time_year_id") REFERENCES "dim_time_year" ("time_year_id");
